### ISSUE TITLE
1

### ISSUE THREAD

**Issue by opencaw** [Jiang-Night/Kernel_driver_hack#10]
1

**Comment by zfdx123** [comment]
没有mmap？？？，你怎么得出这个结论来的

**Comment by Nuthon01** [comment]
移除了vma->vm_next;

**Comment by zfdx123** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=763ecb035029f500d7e6dc99acd1ad299b7726a1

**Comment by zfdx123** [comment]
```
#if(LINUX_VERSION_CODE >= KERNEL_VERSION(6,1,0))
    VMA_ITERATOR(vmi, mm, 0);
    for_each_vma(vmi, vma)
#else
    for (vma = mm->mmap; vma; vma = vma->vm_next)
#endif
    {
        char buf[ARC_PATH_MAX];
        char *path_nm = "";

        if (vma->vm_file) {
            path_nm = file_path(vma->vm_file, buf, ARC_PATH_MAX-1);
            if (!strcmp(kbasename(path_nm), name)) {
                return vma->vm_start;
            }
        }
    }
    return 0;
}
```

也许这样就可以解决？不过我没有测试，只是理论上来说应该这样写，你可以试一下

**Comment by zfdx123** [comment]
https://github.com/Jiang-Night/Kernel_driver_hack/pull/11

**Comment by Nuthon01** [comment]
> ```
> #if(LINUX_VERSION_CODE >= KERNEL_VERSION(6,1,0))
>     VMA_ITERATOR(vmi, mm, 0);
>     for_each_vma(vmi, vma)
> #else
>     for (vma = mm->mmap; vma; vma = vma->vm_next)
> #endif
>     {
>         char buf[ARC_PATH_MAX];
>         char *path_nm = "";
> 
>         if (vma->vm_file) {
>             path_nm = file_path(vma->vm_file, buf, ARC_PATH_MAX-1);
>             if (!strcmp(kbasename(path_nm), name)) {
>                 return vma->vm_start;
>             }
>         }
>     }
>     return 0;
> }
> ```
> 
> 也许这样就可以解决？不过我没有测试，只是理论上来说应该这样写，你可以试一下

移除vma链表
用vma_find（）替换任何vm_next Use。

**Comment by zfdx123** [comment]
> > ```
> > #if(LINUX_VERSION_CODE >= KERNEL_VERSION(6,1,0))
> >     VMA_ITERATOR(vmi, mm, 0);
> >     for_each_vma(vmi, vma)
> > #else
> >     for (vma = mm->mmap; vma; vma = vma->vm_next)
> > #endif
> >     {
> >         char buf[ARC_PATH_MAX];
> >         char *path_nm = "";
> > 
> >         if (vma->vm_file) {
> >             path_nm = file_path(vma->vm_file, buf, ARC_PATH_MAX-1);
> >             if (!strcmp(kbasename(path_nm), name)) {
> >                 return vma->vm_start;
> >             }
> >         }
> >     }
> >     return 0;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 也许这样就可以解决？不过我没有测试，只是理论上来说应该这样写，你可以试一下
> 
> 移除vma链表 用vma_find（）替换任何vm_next Use。

给出你的代码实现？

**Comment by Nuthon01** [comment]
> > > ```
> > > #if(LINUX_VERSION_CODE >= KERNEL_VERSION(6,1,0))
> > >     VMA_ITERATOR(vmi, mm, 0);
> > >     for_each_vma(vmi, vma)
> > > #else
> > >     for (vma = mm->mmap; vma; vma = vma->vm_next)
> > > #endif
> > >     {
> > >         char buf[ARC_PATH_MAX];
> > >         char *path_nm = "";
> > > 
> > >         if (vma->vm_file) {
> > >             path_nm = file_path(vma->vm_file, buf, ARC_PATH_MAX-1);
> > >             if (!strcmp(kbasename(path_nm), name)) {
> > >                 return vma->vm_start;
> > >             }
> > >         }
> > >     }
> > >     return 0;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 也许这样就可以解决？不过我没有测试，只是理论上来说应该这样写，你可以试一下
> > 
> > 移除vma链表 用vma_find（）替换任何vm_next Use。
> 
> 给出你的代码实现？

static size_t get_module_base(pid_t pid, char* name)
{
	struct task_struct* task;
	struct mm_struct* mm;
	struct vm_area_struct *vma;
	size_t count = 0;
	char buf[ARC_PATH_MAX];
	char *path_nm = NULL;

	rcu_read_lock();
	task = pid_task(find_vpid(pid), PIDTYPE_PID);
	if (!task) {
		rcu_read_unlock();
		return 0;
	}
	rcu_read_unlock();

	mm = get_task_mm(task);
	if (!mm) {
		return 0;
	}
	vma = find_vma(mm, 0);
	while (vma) {
		if (vma->vm_file) {
			path_nm = d_path(&vma->vm_file->f_path, buf, ARC_PATH_MAX-1);
			if (!IS_ERR(path_nm) && !strcmp(kbasename(path_nm), name)) {
				count = (uintptr_t)vma->vm_start;
				break;
			}
		}
		if (vma->vm_end >= ULONG_MAX) break; // Prevent wrapping around
		vma = find_vma(mm, vma->vm_end);
	}
	mmput(mm);
	return count;
}
你可以参考一下find_vma的使用，这个支持的。

**Comment by zfdx123** [comment]
> > > > ```
> > > > #if(LINUX_VERSION_CODE >= KERNEL_VERSION(6,1,0))
> > > >     VMA_ITERATOR(vmi, mm, 0);
> > > >     for_each_vma(vmi, vma)
> > > > #else
> > > >     for (vma = mm->mmap; vma; vma = vma->vm_next)
> > > > #endif
> > > >     {
> > > >         char buf[ARC_PATH_MAX];
> > > >         char *path_nm = "";
> > > > 
> > > >         if (vma->vm_file) {
> > > >             path_nm = file_path(vma->vm_file, buf, ARC_PATH_MAX-1);
> > > >             if (!strcmp(kbasename(path_nm), name)) {
> > > >                 return vma->vm_start;
> > > >             }
> > > >         }
> > > >     }
> > > >     return 0;
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 也许这样就可以解决？不过我没有测试，只是理论上来说应该这样写，你可以试一下
> > > 
> > > 
> > > 移除vma链表 用vma_find（）替换任何vm_next Use。
> > 
> > 
> > 给出你的代码实现？
> 
> static size_t get_module_base(pid_t pid, char* name) { struct task_struct* task; struct mm_struct* mm; struct vm_area_struct *vma; size_t count = 0; char buf[ARC_PATH_MAX]; char *path_nm = NULL;
> 
> ```
> rcu_read_lock();
> task = pid_task(find_vpid(pid), PIDTYPE_PID);
> if (!task) {
> 	rcu_read_unlock();
> 	return 0;
> }
> rcu_read_unlock();
> 
> mm = get_task_mm(task);
> if (!mm) {
> 	return 0;
> }
> vma = find_vma(mm, 0);
> while (vma) {
> 	if (vma->vm_file) {
> 		path_nm = d_path(&vma->vm_file->f_path, buf, ARC_PATH_MAX-1);
> 		if (!IS_ERR(path_nm) && !strcmp(kbasename(path_nm), name)) {
> 			count = (uintptr_t)vma->vm_start;
> 			break;
> 		}
> 	}
> 	if (vma->vm_end >= ULONG_MAX) break; // Prevent wrapping around
> 	vma = find_vma(mm, vma->vm_end);
> }
> mmput(mm);
> return count;
> ```
> 
> } 你可以参考一下find_vma的使用，这个支持的。

这样做和我的写法，有性能区别或者提升吗，或者有提高可读性？

**Comment by Nuthon01** [comment]
> > > > > ```
> > > > > #if(LINUX_VERSION_CODE >= KERNEL_VERSION(6,1,0))
> > > > >     VMA_ITERATOR(vmi, mm, 0);
> > > > >     for_each_vma(vmi, vma)
> > > > > #else
> > > > >     for (vma = mm->mmap; vma; vma = vma->vm_next)
> > > > > #endif
> > > > >     {
> > > > >         char buf[ARC_PATH_MAX];
> > > > >         char *path_nm = "";
> > > > > 
> > > > >         if (vma->vm_file) {
> > > > >             path_nm = file_path(vma->vm_file, buf, ARC_PATH_MAX-1);
> > > > >             if (!strcmp(kbasename(path_nm), name)) {
> > > > >                 return vma->vm_start;
> > > > >             }
> > > > >         }
> > > > >     }
> > > > >     return 0;
> > > > > }
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 也许这样就可以解决？不过我没有测试，只是理论上来说应该这样写，你可以试一下
> > > > 
> > > > 
> > > > 移除vma链表 用vma_find（）替换任何vm_next Use。
> > > 
> > > 
> > > 给出你的代码实现？
> > 
> > static size_t get_module_base(pid_t pid, char* name) { struct task_struct* task; struct mm_struct* mm; struct vm_area_struct *vma; size_t count = 0; char buf[ARC_PATH_MAX]; char *path_nm = NULL;
> > 
> > ```
> > rcu_read_lock();
> > task = pid_task(find_vpid(pid), PIDTYPE_PID);
> > if (!task) {
> > 	rcu_read_unlock();
> > 	return 0;
> > }
> > rcu_read_unlock();
> > 
> > mm = get_task_mm(task);
> > if (!mm) {
> > 	return 0;
> > }
> > vma = find_vma(mm, 0);
> > while (vma) {
> > 	if (vma->vm_file) {
> > 		path_nm = d_path(&vma->vm_file->f_path, buf, ARC_PATH_MAX-1);
> > 		if (!IS_ERR(path_nm) && !strcmp(kbasename(path_nm), name)) {
> > 			count = (uintptr_t)vma->vm_start;
> > 			break;
> > 		}
> > 	}
> > 	if (vma->vm_end >= ULONG_MAX) break; // Prevent wrapping around
> > 	vma = find_vma(mm, vma->vm_end);
> > }
> > mmput(mm);
> > return count;
> > ```
> > 
> > } 你可以参考一下find_vma的使用，这个支持的。
> 
> 这样做和我的写法，有性能区别或者提升吗，或者有提高可读性？


find_vma兼容性更强，4.14~6.8都可以使用这个函数的。

**Comment by opencaw** [comment]
> 移除了vma->vm_next;

问一下两位，这个rw33是和这个类似的项目，如果按照你们描述的修改，可以编译通过，但是一旦链接驱动死机，怎么解
https://github.com/abcz316/rwProcMem33/issues/38

**Comment by opencaw** [comment]
> 没有mmap？？？，你怎么得出这个结论来的


问一下两位，这个rw33是和这个类似的项目，如果按照你们描述的修改，可以编译通过，但是一旦链接驱动死机，怎么解
https://github.com/abcz316/rwProcMem33/issues/38

**Comment by zfdx123** [comment]
> > 没有mmap？？？，你怎么得出这个结论来的
> 
> 问一下两位，这个rw33是和这个类似的项目，如果按照你们描述的修改，可以编译通过，但是一旦链接驱动死机，怎么解 [abcz316/rwProcMem33#38](https://github.com/abcz316/rwProcMem33/issues/38)

转到相关项目，并在你的iss下上传kp日志
